env:
  es6: true
  node: true
extends: 'eslint:recommended'
parser: typescript-eslint-parser
parserOptions:
  sourceType: module
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-undef:
    - off
