version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run test
      - npm run build
  post_build:
    commands:
      - npm run clean-dist
      - npm run package
      - aws cloudformation package --template-file samTemplate.yml
                                   --s3-bucket $S3_BUCKET
                                   --s3-prefix CommuteContourDMCach/BuildArtifacts
                                   --output-template-file dist/template.yml

artifacts:
  type: zip
  base-directory: dist
  discard-paths: yes
  files:
    - latest.zip
    - template.yml
